# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI Dev Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  Build:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        java-version: [ 8, 11, 16 ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Set up JDK ${{ matrix.java-version }}"
        uses: actions/setup-java@v2
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B -U package --file pom.xml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SimpleClans
          path: target/SimpleClans.jar

