# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        java-version: [ 11, 16, 21, 23]
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Set up JDK ${{ matrix.java-version }}"
        uses: actions/setup-java@v4
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw -B -U package --file pom.xml
      - name: Upload Build Artifact
        if: "${{ matrix.java-version == 11 }}"
        uses: actions/upload-artifact@v4
        with:
          name: SimpleClans
          path: target/SimpleClans.jar
